"""initial schema

Revision ID: 8f9c28b008e4
Revises: 
Create Date: 2026-07-02 01:10:29.679508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9c28b008e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=120), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('intensity', sa.String(length=16), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_done_at'), ['done_at'], unique=False)
        batch_op.create_index('ix_activity_log_user_done', ['user_id', 'done_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_session_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_session_user_id'), ['user_id'], unique=False)

    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('primary_muscle', sa.String(length=40), nullable=False),
    sa.Column('secondary_muscles', sa.Text(), nullable=True),
    sa.Column('equipment', sa.String(length=32), nullable=False),
    sa.Column('is_main_lift', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_equipment'), ['equipment'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_primary_muscle'), ['primary_muscle'], unique=False)

    op.create_table('meal_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('eaten_at', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_log_eaten_at'), ['eaten_at'], unique=False)
        batch_op.create_index('ix_meal_log_user_eaten', ['user_id', 'eaten_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_log_user_id'), ['user_id'], unique=False)

    op.create_table('nutrition_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=16), nullable=False),
    sa.Column('target_kcal', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_plan_active'), ['active'], unique=False)
        batch_op.create_index('ix_nutrition_plan_user_active', ['user_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_nutrition_plan_user_id'), ['user_id'], unique=False)

    op.create_table('profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('activity_level', sa.String(length=24), nullable=False),
    sa.Column('goal', sa.String(length=16), nullable=False),
    sa.Column('training_goal', sa.String(length=24), nullable=False),
    sa.Column('experience_level', sa.String(length=24), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(length=24), nullable=False),
    sa.Column('units', sa.String(length=16), nullable=False),
    sa.Column('wake_time', sa.String(length=5), nullable=False),
    sa.Column('water_goal_ml', sa.Integer(), nullable=False),
    sa.Column('step_goal', sa.Integer(), nullable=False),
    sa.Column('exercise_goal_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('training_goal', sa.String(length=24), nullable=False),
    sa.Column('split_type', sa.String(length=32), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_active'), ['active'], unique=False)
        batch_op.create_index('ix_program_user_active', ['user_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_program_user_id'), ['user_id'], unique=False)

    op.create_table('sleep_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('wake_time', sa.String(length=5), nullable=False),
    sa.Column('logged_for', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_log_logged_for'), ['logged_for'], unique=False)
        batch_op.create_index('ix_sleep_log_user_day', ['user_id', 'logged_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_log_user_id'), ['user_id'], unique=False)

    op.create_table('step_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('logged_for', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'logged_for', name='uq_step_log_user_day')
    )
    with op.batch_alter_table('step_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_log_user_id'), ['user_id'], unique=False)

    op.create_table('water_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ml', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('water_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_log_logged_at'), ['logged_at'], unique=False)
        batch_op.create_index('ix_water_log_user_at', ['user_id', 'logged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_log_user_id'), ['user_id'], unique=False)

    op.create_table('weight_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('logged_for', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'logged_for', name='uq_weight_log_user_day')
    )
    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_log_user_id'), ['user_id'], unique=False)

    op.create_table('program_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_day_program_id'), ['program_id'], unique=False)

    op.create_table('program_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.String(length=16), nullable=False),
    sa.Column('target_rpe', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('progression', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_exercise_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_program_exercise_program_day_id'), ['program_day_id'], unique=False)

    op.create_table('workout_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('program_day_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_day.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_session_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_session_program_day_id'), ['program_day_id'], unique=False)
        batch_op.create_index('ix_workout_session_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_session_user_id'), ['user_id'], unique=False)

    op.create_table('set_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('set_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_set_log_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_set_log_workout_session_id'), ['workout_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_set_log_workout_session_id'))
        batch_op.drop_index(batch_op.f('ix_set_log_exercise_id'))

    op.drop_table('set_log')
    with op.batch_alter_table('workout_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_session_user_id'))
        batch_op.drop_index('ix_workout_session_user_date')
        batch_op.drop_index(batch_op.f('ix_workout_session_program_day_id'))
        batch_op.drop_index(batch_op.f('ix_workout_session_date'))

    op.drop_table('workout_session')
    with op.batch_alter_table('program_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_exercise_program_day_id'))
        batch_op.drop_index(batch_op.f('ix_program_exercise_exercise_id'))

    op.drop_table('program_exercise')
    with op.batch_alter_table('program_day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_day_program_id'))

    op.drop_table('program_day')
    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_log_user_id'))

    op.drop_table('weight_log')
    with op.batch_alter_table('water_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_log_user_id'))
        batch_op.drop_index('ix_water_log_user_at')
        batch_op.drop_index(batch_op.f('ix_water_log_logged_at'))

    op.drop_table('water_log')
    with op.batch_alter_table('step_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_log_user_id'))

    op.drop_table('step_log')
    with op.batch_alter_table('sleep_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_log_user_id'))
        batch_op.drop_index('ix_sleep_log_user_day')
        batch_op.drop_index(batch_op.f('ix_sleep_log_logged_for'))

    op.drop_table('sleep_log')
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_user_id'))
        batch_op.drop_index('ix_program_user_active')
        batch_op.drop_index(batch_op.f('ix_program_active'))

    op.drop_table('program')
    op.drop_table('profile')
    with op.batch_alter_table('nutrition_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_plan_user_id'))
        batch_op.drop_index('ix_nutrition_plan_user_active')
        batch_op.drop_index(batch_op.f('ix_nutrition_plan_active'))

    op.drop_table('nutrition_plan')
    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_log_user_id'))
        batch_op.drop_index('ix_meal_log_user_eaten')
        batch_op.drop_index(batch_op.f('ix_meal_log_eaten_at'))

    op.drop_table('meal_log')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_primary_muscle'))
        batch_op.drop_index(batch_op.f('ix_exercise_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_name'))
        batch_op.drop_index(batch_op.f('ix_exercise_equipment'))

    op.drop_table('exercise')
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_session_expires_at'))

    op.drop_table('auth_session')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_user_id'))
        batch_op.drop_index('ix_activity_log_user_done')
        batch_op.drop_index(batch_op.f('ix_activity_log_done_at'))

    op.drop_table('activity_log')
    op.drop_table('user')
    # ### end Alembic commands ###
